# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
      #how to set directory path for dotnet restore
        run: dotnet build -projects ./src/Web-API/TLabApp.WebApi/TLabApp.WebApi.csproj
 
        
 
#       MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
#       Error: Process completed with exit code 1
